spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/drilling
    driver-class-name: org.postgresql.Driver
    username: matvey
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
#  mvc:
#    view:
#      prefix: /WEB-INF/jsp/
#      suffix: .jsp